version: '3.8'

services:
  mongo:
    image: mongo:6
    container_name: mongo-local
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: sales-order-api
    depends_on:
      - mongo
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/sales
      - NODE_ENV=prd
    volumes:
      - .:/app
    command: ["node", "dist/main/server.js"]

volumes:
  mongo_data:
